(cl:defpackage ping_sonar-srv
  (:use )
  (:export
   "SENDINGSONARCONFIG"
   "<SENDINGSONARCONFIG-REQUEST>"
   "SENDINGSONARCONFIG-REQUEST"
   "<SENDINGSONARCONFIG-RESPONSE>"
   "SENDINGSONARCONFIG-RESPONSE"
  ))

