// Generated by gencpp from file ping_sonar/sendingSonarConfigResponse.msg
// DO NOT EDIT!


#ifndef PING_SONAR_MESSAGE_SENDINGSONARCONFIGRESPONSE_H
#define PING_SONAR_MESSAGE_SENDINGSONARCONFIGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ping_sonar
{
template <class ContainerAllocator>
struct sendingSonarConfigResponse_
{
  typedef sendingSonarConfigResponse_<ContainerAllocator> Type;

  sendingSonarConfigResponse_()
    : worked(false)  {
    }
  sendingSonarConfigResponse_(const ContainerAllocator& _alloc)
    : worked(false)  {
  (void)_alloc;
    }



   typedef uint8_t _worked_type;
  _worked_type worked;





  typedef boost::shared_ptr< ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator> const> ConstPtr;

}; // struct sendingSonarConfigResponse_

typedef ::ping_sonar::sendingSonarConfigResponse_<std::allocator<void> > sendingSonarConfigResponse;

typedef boost::shared_ptr< ::ping_sonar::sendingSonarConfigResponse > sendingSonarConfigResponsePtr;
typedef boost::shared_ptr< ::ping_sonar::sendingSonarConfigResponse const> sendingSonarConfigResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator1> & lhs, const ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator2> & rhs)
{
  return lhs.worked == rhs.worked;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator1> & lhs, const ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ping_sonar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9488d8ea76faf703564dab31aa285e5";
  }

  static const char* value(const ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9488d8ea76faf70ULL;
  static const uint64_t static_value2 = 0x3564dab31aa285e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ping_sonar/sendingSonarConfigResponse";
  }

  static const char* value(const ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool worked\n"
;
  }

  static const char* value(const ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.worked);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sendingSonarConfigResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ping_sonar::sendingSonarConfigResponse_<ContainerAllocator>& v)
  {
    s << indent << "worked: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.worked);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PING_SONAR_MESSAGE_SENDINGSONARCONFIGRESPONSE_H
