// Generated by gencpp from file ping_sonar/sendingSonarConfigRequest.msg
// DO NOT EDIT!


#ifndef PING_SONAR_MESSAGE_SENDINGSONARCONFIGREQUEST_H
#define PING_SONAR_MESSAGE_SENDINGSONARCONFIGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ping_sonar
{
template <class ContainerAllocator>
struct sendingSonarConfigRequest_
{
  typedef sendingSonarConfigRequest_<ContainerAllocator> Type;

  sendingSonarConfigRequest_()
    : stepSize(0)
    , range(0)  {
    }
  sendingSonarConfigRequest_(const ContainerAllocator& _alloc)
    : stepSize(0)
    , range(0)  {
  (void)_alloc;
    }



   typedef int64_t _stepSize_type;
  _stepSize_type stepSize;

   typedef int64_t _range_type;
  _range_type range;





  typedef boost::shared_ptr< ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator> const> ConstPtr;

}; // struct sendingSonarConfigRequest_

typedef ::ping_sonar::sendingSonarConfigRequest_<std::allocator<void> > sendingSonarConfigRequest;

typedef boost::shared_ptr< ::ping_sonar::sendingSonarConfigRequest > sendingSonarConfigRequestPtr;
typedef boost::shared_ptr< ::ping_sonar::sendingSonarConfigRequest const> sendingSonarConfigRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator1> & lhs, const ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator2> & rhs)
{
  return lhs.stepSize == rhs.stepSize &&
    lhs.range == rhs.range;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator1> & lhs, const ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ping_sonar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8668035c539b1dc98b4832c66a9cd827";
  }

  static const char* value(const ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8668035c539b1dc9ULL;
  static const uint64_t static_value2 = 0x8b4832c66a9cd827ULL;
};

template<class ContainerAllocator>
struct DataType< ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ping_sonar/sendingSonarConfigRequest";
  }

  static const char* value(const ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 stepSize\n"
"int64 range\n"
;
  }

  static const char* value(const ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stepSize);
      stream.next(m.range);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sendingSonarConfigRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ping_sonar::sendingSonarConfigRequest_<ContainerAllocator>& v)
  {
    s << indent << "stepSize: ";
    Printer<int64_t>::stream(s, indent + "  ", v.stepSize);
    s << indent << "range: ";
    Printer<int64_t>::stream(s, indent + "  ", v.range);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PING_SONAR_MESSAGE_SENDINGSONARCONFIGREQUEST_H
