// Generated by gencpp from file ping_sonar/sendingSonarConfig.msg
// DO NOT EDIT!


#ifndef PING_SONAR_MESSAGE_SENDINGSONARCONFIG_H
#define PING_SONAR_MESSAGE_SENDINGSONARCONFIG_H

#include <ros/service_traits.h>


#include <ping_sonar/sendingSonarConfigRequest.h>
#include <ping_sonar/sendingSonarConfigResponse.h>


namespace ping_sonar
{

struct sendingSonarConfig
{

typedef sendingSonarConfigRequest Request;
typedef sendingSonarConfigResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sendingSonarConfig
} // namespace ping_sonar


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ping_sonar::sendingSonarConfig > {
  static const char* value()
  {
    return "6cb2431d101e8b181456b4863d041954";
  }

  static const char* value(const ::ping_sonar::sendingSonarConfig&) { return value(); }
};

template<>
struct DataType< ::ping_sonar::sendingSonarConfig > {
  static const char* value()
  {
    return "ping_sonar/sendingSonarConfig";
  }

  static const char* value(const ::ping_sonar::sendingSonarConfig&) { return value(); }
};


// service_traits::MD5Sum< ::ping_sonar::sendingSonarConfigRequest> should match
// service_traits::MD5Sum< ::ping_sonar::sendingSonarConfig >
template<>
struct MD5Sum< ::ping_sonar::sendingSonarConfigRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ping_sonar::sendingSonarConfig >::value();
  }
  static const char* value(const ::ping_sonar::sendingSonarConfigRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ping_sonar::sendingSonarConfigRequest> should match
// service_traits::DataType< ::ping_sonar::sendingSonarConfig >
template<>
struct DataType< ::ping_sonar::sendingSonarConfigRequest>
{
  static const char* value()
  {
    return DataType< ::ping_sonar::sendingSonarConfig >::value();
  }
  static const char* value(const ::ping_sonar::sendingSonarConfigRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ping_sonar::sendingSonarConfigResponse> should match
// service_traits::MD5Sum< ::ping_sonar::sendingSonarConfig >
template<>
struct MD5Sum< ::ping_sonar::sendingSonarConfigResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ping_sonar::sendingSonarConfig >::value();
  }
  static const char* value(const ::ping_sonar::sendingSonarConfigResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ping_sonar::sendingSonarConfigResponse> should match
// service_traits::DataType< ::ping_sonar::sendingSonarConfig >
template<>
struct DataType< ::ping_sonar::sendingSonarConfigResponse>
{
  static const char* value()
  {
    return DataType< ::ping_sonar::sendingSonarConfig >::value();
  }
  static const char* value(const ::ping_sonar::sendingSonarConfigResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PING_SONAR_MESSAGE_SENDINGSONARCONFIG_H
