// Generated by gencpp from file ping_sonar/SonarRange.msg
// DO NOT EDIT!


#ifndef PING_SONAR_MESSAGE_SONARRANGE_H
#define PING_SONAR_MESSAGE_SONARRANGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ping_sonar
{
template <class ContainerAllocator>
struct SonarRange_
{
  typedef SonarRange_<ContainerAllocator> Type;

  SonarRange_()
    : sonar_range()
    , angle()  {
    }
  SonarRange_(const ContainerAllocator& _alloc)
    : sonar_range(_alloc)
    , angle(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _sonar_range_type;
  _sonar_range_type sonar_range;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::ping_sonar::SonarRange_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ping_sonar::SonarRange_<ContainerAllocator> const> ConstPtr;

}; // struct SonarRange_

typedef ::ping_sonar::SonarRange_<std::allocator<void> > SonarRange;

typedef boost::shared_ptr< ::ping_sonar::SonarRange > SonarRangePtr;
typedef boost::shared_ptr< ::ping_sonar::SonarRange const> SonarRangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ping_sonar::SonarRange_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ping_sonar::SonarRange_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ping_sonar::SonarRange_<ContainerAllocator1> & lhs, const ::ping_sonar::SonarRange_<ContainerAllocator2> & rhs)
{
  return lhs.sonar_range == rhs.sonar_range &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ping_sonar::SonarRange_<ContainerAllocator1> & lhs, const ::ping_sonar::SonarRange_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ping_sonar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ping_sonar::SonarRange_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ping_sonar::SonarRange_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ping_sonar::SonarRange_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ping_sonar::SonarRange_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ping_sonar::SonarRange_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ping_sonar::SonarRange_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ping_sonar::SonarRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "635d4ca17ad4fed19b4f5bcdfb57f952";
  }

  static const char* value(const ::ping_sonar::SonarRange_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x635d4ca17ad4fed1ULL;
  static const uint64_t static_value2 = 0x9b4f5bcdfb57f952ULL;
};

template<class ContainerAllocator>
struct DataType< ::ping_sonar::SonarRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ping_sonar/SonarRange";
  }

  static const char* value(const ::ping_sonar::SonarRange_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ping_sonar::SonarRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] sonar_range # len: 360/step_size, 0->front\n"
"float64[] angle\n"
;
  }

  static const char* value(const ::ping_sonar::SonarRange_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ping_sonar::SonarRange_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sonar_range);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SonarRange_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ping_sonar::SonarRange_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ping_sonar::SonarRange_<ContainerAllocator>& v)
  {
    s << indent << "sonar_range[]" << std::endl;
    for (size_t i = 0; i < v.sonar_range.size(); ++i)
    {
      s << indent << "  sonar_range[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sonar_range[i]);
    }
    s << indent << "angle[]" << std::endl;
    for (size_t i = 0; i < v.angle.size(); ++i)
    {
      s << indent << "  angle[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angle[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PING_SONAR_MESSAGE_SONARRANGE_H
